### ISSUE TITLE
Flow failed after a while

### ISSUE THREAD

**Issue by SPLeon** [cglessner/Microsoft-Flow-Create-Team-Connector#1]
Hi, 

I just installed the custom connector. Everything works fine, but have an issue after a few hours.
I followed the steps of the manual, but after a few hours I have to reconnect in PowerApps, because of the following error:

Failed to refresh access token for service: oauth2. Correlation Id=4bbb4c50-d009-4eb2-b103-2382c06bc9de, UTC TimeStamp=5/15/2018 7:45:24 AM, Error: Missing refresh token.

**Comment by SPLeon** [comment]
Any idea?

**Comment by KbWorks** [comment]
I have exactly the same issue seems the refresh url is not refreshing the token

**Comment by szoghby** [comment]
I have the same problem here, the test works fine inside custom connector, but the flow can not use the connection. Any updates ?

`Unable to process template language expressions in action 'Create_a_Microsoft_Teams' inputs at line '1' and column '2421': 'The template language expression 'json(decodeBase64(triggerOutputs().headers['X-MS-APIM-Tokens']))['$connections']['shared_fb.20microsoft.20teams.<>']['connectionId']' cannot be evaluated because property 'shared_fb.20microsoft.20teams.<>' doesn't exist, available properties are 'shared_sql, shared_approvals, shared_azuread'. Please see https://aka.ms/logicexpressions for usage details.'.`

**Comment by Sjaakos** [comment]
I also experience the same issue, anyone has an solution?

**Comment by Larryngolog** [comment]
I have a tested solution. When you add app permissions in AAD panel select also the "access user's data anytime" permission as well. This way your token would be automatically refreshed. Remember that if you change the permissions, you need to approve them in AAD panel and reauthenticate the connection in Flow.

**Comment by ltwlf** [comment]
@Larryngolog thanks for your support! You are right, this allows to renew the token without user interaction. I've updated the documentation.

**Comment by Larryngolog** [comment]
For me adding the "access user's data anytime" didn't solve the issue after all. I still have to reenter the credentials after 1hr. Strange, as it helped for 1 day. I event recreated app in Azure Ad and connector in Power Apps, but it did not help.

**Comment by Sjaakos** [comment]
> For me adding the "access user's data anytime" didn't solve the issue after all. I still have to reenter the credentials after 1hr. Strange, as it helped for 1 day. I event recreated app in Azure Ad and connector in Power Apps, but it did not help.

Same here, I deleted the flow, the app registration & the custom connector. Then re-created it but after 1 hour the connection is 'broken'. 
![image](https://user-images.githubusercontent.com/44272712/48932598-174f2700-eefd-11e8-9445-2559e0b30bef.png)
I also added & granted all the rest of the permissions to test if it solved anything but it didn't.

**Comment by Larryngolog** [comment]
I do not know why, but after I have removed the connection completely from Flow and then created activity again it stopped timing out. I think I did it the same way in the past and it did not help. Now for some magical reason it works. My connection has been working for 4 days now without an issue.

**Comment by ltwlf** [comment]
Unfortunately the deployment of custom connectors can sometimes be really tedious. I had the same experience with deleting and redeployment. Microsoft use internally a proxy which cache cache some settings, sometime the changes works just after a while. Often I just delete an redeploy to be sure that it is not a caching problem.

**Comment by adamtobia5** [comment]
Hello,

First off, just wanted to say thanks to those that worked on this connector. 

Its great when getting this to work, but recently I've been experiencing the following issue. Has this been fixed? @ltwlf when you delete and redeploy, does the issue persist?

**Comment by ltwlf** [comment]
Hello @adamtobia5 

did you try to set the "access user's data anytime" permission flag and recreate the connection? In general Flow should handle the token refresh process. But even the Connections of the official Microsoft connectors break sometimes. 

Best wishes
Christian
