### ISSUE TITLE
Installation Step 1 - more information

### ISSUE THREAD

**Issue by bernardw1** [cglessner/Microsoft-Flow-Create-Team-Connector#2]
Thank you for creating this Flow connector. It should be really nice to use.

I was wondering if you could add a bit more information to the installation Step 1 > Register App in Azure Portal
I am guessing this app needs to be in portal found at https://apps.dev.microsoft.com

It looks like we should skip the Guided creation.

The application ID and the Application Secret can be found at the top of the next page
![image](https://user-images.githubusercontent.com/23319226/42535792-02167616-8456-11e8-810a-bdc03d0829dd.png)

**Comment by bernardw1** [comment]
Well coming back to this after a while to see if I can get it working. I am able to get it working but the steps are now a bit different then they were originally (thanks MS for changing things again)

To create the Azure APP

go to the Azure Portal https://protal.azure.com
Go to Azure Active Directory
Go to App Registrations
Create a new Application Registration
![image](https://user-images.githubusercontent.com/23319226/46364074-57e79e00-c63a-11e8-83e9-3b722c77a6af.png)

Just fill anything in for the Sign-on URL for example https://test.com

Create the app.

in the new App click on Settings
Go to required permissions
click Add
Select an API > "Microsoft Graph"
Select Permission > scroll down and add the permission for "Read and write all groups" 
![image](https://user-images.githubusercontent.com/23319226/46364448-70a48380-c63b-11e8-8e9b-a83669e5d15c.png)
click on "Grant Permissions"

Go to Settings>Keys> Create a new key (add a description), click save and copy the value (make sure to keep this safe it will be needed later).

Go to Settings > properties > Copy the Application ID, this will also be needed later

After finishing step 2 you will need to copy the "Reply URL" from there and add it to Settings>Reply URLs> so that the application can be authenticated.

**Comment by Larryngolog** [comment]
I recommend adding also permissions "access user's data anytime" so your token would be refreshed automatically after it expires after one hour.

**Comment by ltwlf** [comment]
@Larryngolog is right. This should do the trick!

**Comment by bernardw1** [comment]
@ltwlf  The issue is not that that setting is wrong. the issue that I created this thread for was that the initial documentation was not complete enough to know what steps needed to be taken to get the azure AD stuff setup. That is the reason I created the thread, to help other people setup the application and know where to go to do it.
